version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        volumes:
            - mongo:/data/db
    recipe-api:
        build: .
        ports:
            - '3000:3000'
        container_name: recipe-api
volumes:
    mongo:
