version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        volumes:
            - mongo:/data/db
    recipe-api:
        image: docker.pkg.github.com/battmeech/recipe-api/recipe-api:latest
        ports:
            - '3000:3000'
        container_name: recipe-api
volumes:
    mongo:
